image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ./creds
  - echo $SERVICEACCOUNT_bigquery | base64 -d > ./creds/serviceaccount.json
  - terraform init


stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate
  tags:
    - docker_build
  only:
  #  - develop
  #  - bigquery-branch
    - master
        
plan:
  stage: plan
  script:
    - terraform plan -var-file=terraform.tfvars -var project=${PROJECT_ID} -out "planfile"
   
  dependencies:
    - validate
  
  artifacts:
    paths:
      - planfile
  tags:
    - docker_build
  only:
  #  - develop
  #  - bigquery-branch
    - master

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual
  tags:
    - docker_build
  only:
   # - develop
  #  - bigquery-branch  
    - master
